add new service on cont-init

diff --git a/videoserver/rootfs/etc/services.d/videoserver/run b/videoserver/rootfs/etc/services.d/videoserver/run
--- a/videoserver/rootfs/etc/services.d/videoserver/run
+++ b/videoserver/rootfs/etc/services.d/videoserver/run
@@ -3,44 +3,8 @@
 # Start videoserver service
 # ==============================================================================
 
-fast="-preset ultrafast"
-vidcopy="-c copy"
+echo "Starting ffserver"
 
+ffserver
 
-function startStream()
-{
-        while [ ! -f /run/stopserver ] ; do
-                sleep 1s
-                echo "start ffmpeg $1 from input: $2"
-                ffmpeg -i "$2" $vidcopy $fast -strict -2 "http://localhost:8090/$1.ffm"
-                echo "ffmpeg exit done errorcode: $?"
-        done
-}
-
-
-function parseFFMpegConf()
-{
-        json=/data/options.json
-        for row in $(jq -cr '.video_sources[]' $json); do
-                name=$(echo $row | jq -r '.name')
-                input=$(echo $row | jq -r '.input')
-
-                if [[ -n "$name" && -n "$input" ]] ; then
-                        startStream "$name" "$input" &
-                else
-                        echo "Error invalid config, misssing name or input: $row"
-                fi
-        done
-}
-
-
-echo "starting ffmpeg feeds ..."
-
-parseFFMpegConf
-
-echo "starting ffserver ..."
-while [ ! -f /run/stopserver ] ; do
-	ffserver
-	sleep 1s
-done
-echo "ffserver loop terminated"
+echo "ffserver exited, errorcode: $?"
